### ISSUE TITLE
How to open ASC file?

### ISSUE THREAD

**Issue by neovash23** [MintcoinCommunity/Mintcoin-Desktop-Wallet#120]
I can't seem to find an simple way of opening the ASC file for me to install the wallet. anyone?

**Comment by shane-kerr** [comment]
The ASC file is the PGP signature for the file with the same name, without the `.asc` on the end.

You probably want to download the Windows setup file here: https://github.com/MintcoinCommunity/Mintcoin-Desktop-Wallet/releases/download/v2.1.1/MintCoin-2.1.1-win32-setup.exe
