### ISSUE TITLE
wallet wont sync

### ISSUE THREAD

**Issue by etherbinge** [MintcoinCommunity/Mintcoin-Desktop-Wallet#22]
upgraded mintcoin wallet still saying out of sync please help i have sent a lot of mintcoin to this wallet

**Comment by Fuzzbawls** [comment]
please provide some details

**Comment by etherbinge** [comment]
i have just installed the new wallet sent what I have from poloniex because they are not supporting it I assumed my wallet would just sync but it is reading out of sync in red and I am not quite sure how to get it too sync any more info needed ?

**Comment by etherbinge** [comment]
running windows

**Comment by Fuzzbawls** [comment]
What Version?
How many connections?
Is this a completely fresh install or an upgrade?
If upgrading, from what version?
Are you trying to sync from the network or using a bootstrap?

**Comment by etherbinge** [comment]
v2.0.2.0
0 active connections saying wallet is offline 
fresh install
no bootstrap

**Comment by Fuzzbawls** [comment]
Either your computer cannot resolve the DNS hostname to fetch initial peers, or you have a firewall blocking the program (or both)

post your debug.log file's contents. The file can be found at the following location:
C:\Documents and Settings\YourUserName\Application data\MintCoin (XP)
C:\Users\YourUserName\Appdata\Roaming\MintCoin (Vista and 7)

**Comment by etherbinge** [comment]
I  am running windows 10

**Comment by Fuzzbawls** [comment]
same place as the Vista and Windows 7 location

**Comment by Fuzzbawls** [comment]
Marking this as closed due to no more information having been submitted. If the problem is persisting, please comment again

**Comment by sunsetjunks** [comment]
How about settings for Mac?

**Comment by SKBMB** [comment]
Hello, i just experienced the same issue on windows 10. 
Mintcoin wallet is not connecting and so not synchronizing. It's version 2.0.2.0 and QT 5.4.2 in case that's relevant as well.

I can provide an error log if that's required. Thanks a lot !
