### ISSUE TITLE
MintCoin Wallet not Syncing.  Sent mintcoin to wallet yesterday.

### ISSUE THREAD

**Issue by waayenbe** [MintcoinCommunity/Mintcoin-Desktop-Wallet#31]
I've downloaded the mintcoin wallet and sent mintcoin from cryptopia to the wallet address.  The wallet does not seem to be syncing.  I've followed some of the instruction I've found laying around but can't seem to figure it out.  Can anyone help?

**Comment by griffith90** [comment]
i have a same problem i also cheked firewall and snapshot also extracted and add node conf 
but active connection is zero and there's no differences in korea there are 2 or 3 like me
plz solve this problem...

**Comment by jorge8mc** [comment]
I have the same problem. I downloaded the wallet and transferred my mint coins from Cryptopia yesterday, but the wallet does not sync and show 0 balance!
What's going on?

**Comment by SoundJudgement** [comment]
i also have the same problem, i have just downloaded mintcoin qt and configured config file as per the daemon, and it isn't connecting and 0 peers. i am windows 7 and here is my log file:


MintCoin version v2.0.2.0 (2016-02-23 23:48:07 -0800)
Using OpenSSL version OpenSSL 1.0.2d 9 Jul 2015
Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
Startup time: 01/18/18 18:23:43
Default data directory C:\Users\Lee\AppData\Roaming\MintCoin
Used data directory C:\Users\Lee\AppData\Roaming\MintCoin
dbenv.open LogDir=C:\Users\Lee\AppData\Roaming\MintCoin\database ErrorFile=C:\Users\Lee\AppData\Roaming\MintCoin\db.log
Bound to [::]:12788
Bound to 0.0.0.0:12788
Loading block index...
Opening LevelDB in C:\Users\Lee\AppData\Roaming\MintCoin\txleveldb
Opened LevelDB successfully
CBlock(hash=af4ac34e7ef10a08fe2ba692eb9a9c08cf7e89fcf352f9ea6f0fd73ba3e5d03c, ver=1, hashPrevBlock=0000000000000000000000000000000000000000000000000000000000000000, hashMerkleRoot=cf174ca43b1b30e9a27f7fdc20ff9caf626499d023f1f033198fdbadf73ca747, nTime=1391393693, nBits=1e0fffff, nNonce=12488421, vtx=1, vchBlockSig=)
  Coinbase(hash=cf174ca43b, nTime=1391393673, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 04ffff001d020f274cad46656220322c20323031343a205468652044656e7665722042726f6e636f732066696e616c6c7920676f74206f6e2074686520626f6172642077697468206120746f756368646f776e20696e207468652066696e616c207365636f6e6473206f662074686520746869726420717561727465722e20427574207468652053656174746c65205365616861776b732061726520646f6d696e6174696e67207468652042726f6e636f732033362d38)
    CTxOut(empty)
  vMerkleTree: cf174ca43b 
block.GetHash() == af4ac34e7ef10a08fe2ba692eb9a9c08cf7e89fcf352f9ea6f0fd73ba3e5d03c
block.hashMerkleRoot == cf174ca43b1b30e9a27f7fdc20ff9caf626499d023f1f033198fdbadf73ca747
block.nTime = 1391393693 
block.nNonce = 12488421 
Opening LevelDB in C:\Users\Lee\AppData\Roaming\MintCoin\txleveldb
Opened LevelDB successfully
SetBestChain: new best=af4ac34e7ef10a08fe2ba692eb9a9c08cf7e89fcf352f9ea6f0fd73ba3e5d03c  height=0  trust=0000000000000000000000000000000000000000000000000000000000000001  date=02/03/14 02:14:53
Stake checkpoint: fd11f4e7
ResetSyncCheckpoint: pending for sync-checkpoint 07b3ab4d6bd9d7ae835b320e9371e1bb4258ffbad975ec0422f71a21d1900017
ResetSyncCheckpoint: sync-checkpoint reset to af4ac34e7ef10a08fe2ba692eb9a9c08cf7e89fcf352f9ea6f0fd73ba3e5d03c
 block index             113ms
Loading wallet...
nFileVersion = 2000200
Performing wallet upgrade to 60000
keypool added key 1, size=1
keypool added key 2, size=2
keypool added key 3, size=3
keypool added key 4, size=4
keypool added key 5, size=5
keypool added key 6, size=6
keypool added key 7, size=7
keypool added key 8, size=8
keypool added key 9, size=9
keypool added key 10, size=10
keypool added key 11, size=11
keypool added key 12, size=12
keypool added key 13, size=13
keypool added key 14, size=14
keypool added key 15, size=15
keypool added key 16, size=16
keypool added key 17, size=17
keypool added key 18, size=18
keypool added key 19, size=19
keypool added key 20, size=20
keypool added key 21, size=21
keypool added key 22, size=22
keypool added key 23, size=23
keypool added key 24, size=24
keypool added key 25, size=25
keypool added key 26, size=26
keypool added key 27, size=27
keypool added key 28, size=28
keypool added key 29, size=29
keypool added key 30, size=30
keypool added key 31, size=31
keypool added key 32, size=32
keypool added key 33, size=33
keypool added key 34, size=34
keypool added key 35, size=35
keypool added key 36, size=36
keypool added key 37, size=37
keypool added key 38, size=38
keypool added key 39, size=39
keypool added key 40, size=40
keypool added key 41, size=41
keypool added key 42, size=42
keypool added key 43, size=43
keypool added key 44, size=44
keypool added key 45, size=45
keypool added key 46, size=46
keypool added key 47, size=47
keypool added key 48, size=48
keypool added key 49, size=49
keypool added key 50, size=50
keypool added key 51, size=51
keypool added key 52, size=52
keypool added key 53, size=53
keypool added key 54, size=54
keypool added key 55, size=55
keypool added key 56, size=56
keypool added key 57, size=57
keypool added key 58, size=58
keypool added key 59, size=59
keypool added key 60, size=60
keypool added key 61, size=61
keypool added key 62, size=62
keypool added key 63, size=63
keypool added key 64, size=64
keypool added key 65, size=65
keypool added key 66, size=66
keypool added key 67, size=67
keypool added key 68, size=68
keypool added key 69, size=69
keypool added key 70, size=70
keypool added key 71, size=71
keypool added key 72, size=72
keypool added key 73, size=73
keypool added key 74, size=74
keypool added key 75, size=75
keypool added key 76, size=76
keypool added key 77, size=77
keypool added key 78, size=78
keypool added key 79, size=79
keypool added key 80, size=80
keypool added key 81, size=81
keypool added key 82, size=82
keypool added key 83, size=83
keypool added key 84, size=84
keypool added key 85, size=85
keypool added key 86, size=86
keypool added key 87, size=87
keypool added key 88, size=88
keypool added key 89, size=89
keypool added key 90, size=90
keypool added key 91, size=91
keypool added key 92, size=92
keypool added key 93, size=93
keypool added key 94, size=94
keypool added key 95, size=95
keypool added key 96, size=96
keypool added key 97, size=97
keypool added key 98, size=98
keypool added key 99, size=99
keypool added key 100, size=100
keypool added key 101, size=101
 wallet                 9363ms
Loading addresses...
ERROR: CAddrman::Read() : open failed
Invalid or missing peers.dat; recreating
Loaded 0 addresses from peers.dat  0ms
mapBlockIndex.size() = 1
nBestHeight = 0
setKeyPool.size() = 100
mapWallet.size() = 0
mapAddressBook.size() = 1
send version message: version 60007, blocks=0, us=0.0.0.0:0, them=0.0.0.0:0, peer=127.0.0.1:0
socket send error 10038
Done loading
ThreadDNSAddressSeed started
Loading addresses from DNS seeds (could take a while)
ThreadOpenConnections started
ThreadOpenAddedConnections started
ThreadOpenAddedConnections exited
ThreadSocketHandler started
ThreadMessageHandler started
ThreadStakeMinter started
CPUMiner started for proof-of-stake
Flushed 0 addresses to peers.dat  21ms
refreshWallet
ipcThread started
Flushing wallet.dat
Flushed wallet.dat 115ms
connection timeout
ERROR: GetMyExternalIP() : connection to 91.198.22.70:80 failed
connection timeout
ERROR: GetMyExternalIP() : connection to 74.208.43.192:80 failed
GetMyExternalIP() received [31.205.1.243] 31.205.1.243:0
GetMyExternalIP() returned 31.205.1.243
AddLocal(31.205.1.243:12788,4)
0 addresses found from DNS seeds
ThreadDNSAddressSeed exited
Flushed 0 addresses to peers.dat  34ms
Flushed 0 addresses to peers.dat  32ms
Flushed 0 addresses to peers.dat  19ms
Flush(false)
DBFlush(false) ended               0ms
StopNode()
ThreadSocketHandler exited
ThreadMessageHandler exited
ipcThread exited
ThreadStakeMinter exiting, 0 threads remaining
ThreadOpenConnections exited
Flushed 0 addresses to peers.dat  20ms
Flush(true)
DBFlush(true) ended               0ms
MintCoin exited

**Comment by goldenmycelium** [comment]
same problem

**Comment by waayenbe** [comment]
Go to the Mintcoin's telegram

https://t.me/OfficialMintcoin

They helped me figure it out and now mine is sync'd
