### ISSUE TITLE
Compile-Error: init.cpp:556:15: error: operator '!' has no right operand

### ISSUE THREAD

**Issue by typoworx-de** [MintcoinCommunity/Mintcoin-Desktop-Wallet#33]
tested on master an tag/branch v2.0.2.

```
init.cpp:556:15: error: operator '!' has no right operand
makefile.unix:163: recipe for target 'obj/init.o' failed
make: *** [obj/init.o] Error 1
```

**Comment by shane-kerr** [comment]
Confirmed. I have fixed this in my own branch with this commit:

https://github.com/shane-kerr/Mintcoin-Desktop-Wallet/commit/8bc46dfa9c43e5d06b107279dc71521dcb3019d4

**Comment by shane-kerr** [comment]
This issue has been fixed. The current 2.0 branch should build without the error.
