### ISSUE TITLE
AHHHHHHHHHHHHHHH

### ISSUE THREAD

**Issue by dr3ad3d** [MintcoinCommunity/Mintcoin-Desktop-Wallet#72]
I have tried EVERYTHING !!!! I cant CONNNECtttt Please some one help me ?

**Comment by rodrigolisp** [comment]
If you are on Windows, close your wallet, open %appdata%/mintcoin, paste the file MintCoin.conf (inside the zip) and then open your wallet.
You can use a blockchain snapshot to sync faster: visit https://www.reddit.com/r/MintCoin/ for more details.
[MintCoin_conf.zip](https://github.com/MintcoinCommunity/Mintcoin-Desktop-Wallet/files/2114856/MintCoin_conf.zip)
